export const BAIRROS: Array<string> = [
  "Açude",
  "Água Preta",
  "Anhumas",
  "Área Rual",
  "Avenida",
  "Boa Vista",
  "Bps",
  "Capituba",
  "Centro",
  "Cruzeiro",
  "Distrito Industrial",
  "Estiva",
  "Ilhéus",
  "Imbel",
  "Jardim América",
  "Jardim Bernadete",
  "Jardim Colinas",
  "Jardim Nações",
  "Jardim Palmeiras",
  "Jardim Paraíso",
  "Loteamento Felippe Jacob",
  "Loteamento José H Ricota",
  "Loteamento Sapucaí",
  "Medicina",
  "Moquem",
  "Morro Chic",
  "Morro Grande",
  "Nações",
  "Nossa Senhora da Agonia",
  "Nossa Senhora de Fátima",
  "Nossa Senhora de Lourdes",
  "Novo Horizonte",
  "Oriente",
  "Pedra Mamona",
  "Piedade",
  "Pinheirinho",
  "Porto Velho",
  "Rebourgeon",
  "Santa Helena",
  "Santa Luzia",
  "Santa Rita de Cássia",
  "Santa Rosa",
  "Santa Verde",
  "Santo Antônio",
  "Santos Dummont",
  "São Sebastião",
  "São Vicente",
  "Varginha",
  "Vila Isabel",
  "Vila Poddis",
  "Vila Rubens"
]